<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="49250" started-at="2021-04-23T01:44:34Z" finished-at="2021-04-23T01:45:23Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="49250" started-at="2021-04-23T01:44:34Z" finished-at="2021-04-23T01:45:23Z">
      <class name="testcases.TC002Payee">
        <test-method status="PASS" signature="addPayee()[pri:0, instance:testcases.TC002Payee@4e3958e7]" name="addPayee" duration-ms="13556" started-at="2021-04-23T01:44:34Z" finished-at="2021-04-23T01:44:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addPayee -->
      </class> <!-- testcases.TC002Payee -->
      <class name="testcases.TC001Login_NegativeScenario">
        <test-method status="FAIL" signature="verifyLoginFailure()[pri:0, instance:testcases.TC001Login_NegativeScenario@1dac5ef]" name="verifyLoginFailure" duration-ms="2602" started-at="2021-04-23T01:45:05Z" finished-at="2021-04-23T01:45:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Zero - Account Summary] but found [Zero - Log in]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Zero - Account Summary] but found [Zero - Log in]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testcases.TC001Login_NegativeScenario.verifyLoginFailure(TC001Login_NegativeScenario.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginFailure -->
      </class> <!-- testcases.TC001Login_NegativeScenario -->
      <class name="testcases.TC004PurchaseCurrency">
        <test-method status="PASS" signature="PurchaseCurrency()[pri:0, instance:testcases.TC004PurchaseCurrency@5c90e579]" name="PurchaseCurrency" duration-ms="12328" started-at="2021-04-23T01:45:07Z" finished-at="2021-04-23T01:45:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PurchaseCurrency -->
      </class> <!-- testcases.TC004PurchaseCurrency -->
      <class name="testcases.TC001Login">
        <test-method status="PASS" signature="verifyLogin()[pri:0, instance:testcases.TC001Login@58ea606c]" name="verifyLogin" duration-ms="3524" started-at="2021-04-23T01:45:20Z" finished-at="2021-04-23T01:45:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
      </class> <!-- testcases.TC001Login -->
      <class name="testcases.TC003PayBills">
        <test-method status="PASS" signature="PayAddPayee()[pri:0, instance:testcases.TC003PayBills@77f80c04]" name="PayAddPayee" duration-ms="16806" started-at="2021-04-23T01:44:48Z" finished-at="2021-04-23T01:45:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PayAddPayee -->
      </class> <!-- testcases.TC003PayBills -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
